name: Run CI tests

on:
  push:
    branches:
      - master
      - add-ci-test-setup
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      KEYCLOAK_HOST: localhost
      KEYCLOAK_PORT: 8080
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_REALM: test-realm
      KEYCLOAK_CLIENT_ID: test-client
      KEYCLOAK_CLIENT_SECRET_KEY: f6974574-c773-4554-826d-06946cd55e98
    strategy:
      max-parallel: 2
      matrix:
        # python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.7"]
        keycloak-tag:
          [
            # "10.0.2",
            # "11.0.3",
            # "12.0.4",
            "13.0.1",
            # "14.0.0",
            # "15.1.1",
            # "16.1.1",
            # "17.0.1-legacy",
            # "18.0.2-legacy",
            # "19.0.3-legacy",
          ]

    services:
      keycloak:
        image: quay.io/keycloak/keycloak:${{ matrix.keycloak-tag }}
        ports:
          - 8080:8080
          - 9990:9990
        options: >-
          -e "KEYCLOAK_USER=admin"
          -e "KEYCLOAK_PASSWORD=admin"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up the cache
        uses: actions/cache@v1
        env:
          cache-name: cache-python-packages
        with:
          path: .venv
          key: poetry-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Set up the project
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: Test with pytest
        run: ./tests/start.sh
